version: '3.9'

networks:
  proxy:
    name: backbone_proxy
    external: true
  database:
    name: backbone_database
    external: true

services:
  runner:
    image: gitea/act_runner:0.2.8
    container_name: gitea_runner
    restart: always
      #volumes:
      #- "./gitea:/data"
      #- "/home/git/.ssh/id_rsa.pub:/data/git/.ssh/authorized_keys"
      #- "/home/git/.ssh/:/data/git/.ssh"
    labels:
      - traefik.enable=false
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.rule=Host("${APPLICATION_FQDN}")
      - traefik.http.routers.gitea.service=gitea-service
      - traefik.http.services.gitea-service.loadbalancer.server.port=3000
    environment:
      TZ: Europe/Berlin
      # START Dual Setup with nginx proxy 
      VIRTUAL_HOST: ${APPLICATION_FQDN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${APPLICATION_FQDN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_MAIL}
      # END
      USER_UID: 9001 
      USER_GID: 9001
      USER: git
      GITEA__server__ROOT_URL: https://${APPLICATION_FQDN}
      GITEA__server__DOMAIN: ${APPLICATION_FQDN}
      GITEA__server__SSH_DOMAIN: ${APPLICATION_FQDN}
      GITEA__server__SSH_CREATE_AUTHORIZED_KEYS_FILE: false
      GITEA__security__MIN_PASSWORD_LENGTH: 12 
      GITEA__security__PASSWORD_COMPLEXITY: 'lower,upper,digit,spec'
      GITEA__security__INSTALL_LOCK: true
      GITEA__log__LEVEL: Info 
      GITEA__admin__DISABLE_REGULAR_ORG_CREATION: true
      GITEA__openid__ENABLE_OPENID_SIGNIN: false 
      GITEA__openid__ENABLE_OPENID_SIGNUP: true 
      GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION: true
      GITEA__oauth2_client__ACCOUNT_LINKING: 'login' 
      GITEA__oauth2_ENABLE: false
      GITEA__service__REQUIRE_SIGNIN_VIEW: true
      GITEA__service__ENABLE_NOTIFY_MAIL: true
      GITEA__service__ENABLE_BASIC_AUTHENTICATION: false
      GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE: false 
      GITEA__service__SHOW_REGISTRATION_BUTTON: false 
      GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: true 
      GITEA__service__ALLOWED_USER_VISIBILITY_MODES: 'public,limited'
      GITEA__service__DEFAULT_ORG_MEMBER_VISIBLE: true
      GITEA__database__DB_TYPE: ${DB_TYPE:-sqlite3}
      GITEA__database__HOST: ${DB_HOST:-mariadb}
      GITEA__database__NAME: ${DB_NAME:-giteadb}
      GITEA__database__USER: ${DB_USER:-gitea}
      GITEA__database__PASSWD: ${DB_PASSWD}
    networks:
      - proxy
      - database
    ports:
      - "127.0.0.1:2222:22"
