version: '3.9'

services:
  runner:
    image: gitea/act_runner:0.2.10
    container_name: gitea_runner
    restart: always
    volumes:
      - "./runner:/data"
      - "./config.yaml:/config.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Europe/Berlin
      CONFIG_FILE: "/config.yaml" 
      GITEA_INSTANCE_URL: "https://${GITEA_FQDN}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${RUNNER_TOKEN}"
      GITEA_RUNNER_NAME: "${RUNNER_NAME}"
      GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
